# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mac Client

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B install -Dinstaller=true --file pom.xml
    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: DMG file
        path: target/installer/*.dmg
    - name: Upload PKG
      uses: actions/upload-artifact@v2
      with:
        name: PKG file
        path: target/installer/*.pkg